### ISSUE TITLE
File always redownloads, and re-extracts when agent is run

### ISSUE THREAD

**Issue by felipe1982** [camptocamp/puppet-archive#55]
It should run once, when files do not exist in $target_dir. however, it always runs. Why is this?

**Comment by mazilu88** [comment]
I have the same issue, is there a workaround?

**Comment by Conzar** [comment]
Same issue here.

**Comment by Conzar** [comment]
Ok, the problem is this.
If your zip file doesn't create a directory, than the archive::extract module will constantly unzip the directory. This is due to the 'creates' parameter on the exec resource that does the unzipping.

I think the documentation needs to be cleared up on this or maybe add an additional parameter that states the archive doesn't create a directory.

@felipe1982  & @mazilu88  Anyways, the work-a-round is to define the root_dir.  See sudo-code below:
```
  # download and unzip
  archive {'name':
...
    target         => <TARGET DIRECTORY>,
    root_dir      => '.',
...
  }
```

**Comment by ayashjorden** [comment]
Worked for me, thank you @Conzar

**Comment by raphink** [comment]
Can this be closed, or do you want to suggest a PR for the README?
